# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  boot:
    taskfile: ./pkg/boot/Taskfile.yml
    dir: ./pkg/boot
  httpsvr:
    taskfile: ./pkg/httpsvr/Taskfile.yml
    dir: ./pkg/httpsvr
  inertia:
    taskfile: ./pkg/inertia/Taskfile.yml
    dir: ./pkg/inertia
  template:
    taskfile: ./internal/scaffold/template/Taskfile.yml
    dir: ./internal/scaffold/template

tasks:
  linter:
    desc: Run linters
    cmds:
      - task: boot:linter
      - task: httpsvr:linter
      - task: inertia:linter
      - task: template:linter
    silent: true

  test:
    desc: Run tests
    cmds:
      - task: boot:test
      - task: httpsvr:test
      - task: inertia:test
      - task: template:test
    silent: true

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - task: boot:test:coverage
      - task: httpsvr:test:coverage
      - task: inertia:test:coverage
      - task: template:test:coverage
    silent: true

  apm:install:
    desc: Install APM packages
    cmds:
      - apm install
    silent: true

  apm:compile:
    desc: Compile APM packages
    cmds:
      - apm compile
    silent: true

  update:go:*:
    desc: Update go.mod go version in all modules
    vars:
      VERSION: '{{index .MATCH 0}}'
    cmds:
      - task: mod:update:go:{{.VERSION}}
      - task: boot:mod:update:go:{{.VERSION}}
      - task: httpsvr:mod:update:go:{{.VERSION}}
      - task: inertia:mod:update:go:{{.VERSION}}
      - task: template:mod:update:go:{{.VERSION}}
    silent: true

  mod:update:go:*:
    desc: Update go.mod go version
    vars:
      VERSION: '{{index .MATCH 0}}'
    cmds:
      - go mod edit -go={{.VERSION}}
    silent: true
